apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}

    spec:
      serviceAccountName: {{ .Chart.Name }}

      containers:
      - name: {{ .Chart.Name }}

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          {{- toYaml .Values.resources | nindent 10 }}